### ISSUE TITLE
样式压缩合并规则导致微信小程序端样式失效

### ISSUE THREAD

**Issue by iamonox** [didi/chameleon#262]
minimize:true构建时，使用OptimizeCssAssetsPlugin处理了样式文件，然而OptimizeCssAssetsPlugin默认启用了mergeRules规则，会合并相邻选择器的相同规则。
若在多态组件微信小程序端使用如下样式：
```css
:host{
  height:100%;
  width:100%;
  overflow:hidden;
}
.demo-com {
  height:100%;
  width:100%;
  overflow:hidden;
  display: flex;
}
```
会被处理成
```css
.demo-com,:host{height:100%;width:100%;overflow:hidden}.demo-com{display: flex}
```

:host和其他选择器一起时，这规则会无效
似乎不是微信端独有的问题：https://github.com/cssnano/cssnano/issues/730

禁用OptimizeCssAssetsPlugin的mergeRules规则就正常了
```js
webpackConfig.plugins.forEach(plugin=>{
    if(plugin.constructor.name === 'OptimizeCssAssetsPlugin'){
        plugin.options.cssProcessorOptions.mergeRules = false
    }
})
```
