### ISSUE TITLE
使用carousel组件时，在H5端自动轮播两分钟不到就报错

### ISSUE THREAD

**Issue by Bian2017** [didi/chameleon#86]
**bug描述**
使用carousel组件时，在H5端轮播两分钟不到就开始报如下错误，在其他小程序端均无此问题。报错后，自动轮播功能会失效。

代码如下：
![image](https://user-images.githubusercontent.com/28329190/54591697-bfb56800-4a65-11e9-8745-d658bee5f529.png)

**问题截图**
![image](https://user-images.githubusercontent.com/28329190/54591683-b2987900-4a65-11e9-9108-c0a06d014887.png)

**编译环境信息**
 - chameleon-tool 版本：chameleon-tool@0.1.0-alpha.4
- 依赖
  "dependencies": {
    "chameleon-api": "^0.3.0-alpha.0",
    "chameleon-bridge": "^0.1.0",
    "chameleon-runtime": "0.0.4",
    "chameleon-store": "0.0.3",
    "chameleon-ui-builtin": "0.0.7-alpha",
    "cml-ui": "0.0.7-alpha"
  }

后将chameleon-ui-builtin更新至0.0.7-alpha.5，发现虽然不报错了，但是运行几分钟后轮播图的自动轮播功能依旧会失效。

**Comment by beatles-chameleon** [comment]
无法复现。
能否微信/QQ联系发一下相关代码，或者直接提交到github查看

**Comment by Bian2017** [comment]
> 无法复现。
> 能否微信/QQ联系发一下相关代码，或者直接提交到github查看

```
  <view class="banner-container">
            <carousel
              class="banner-carousel"
              indicator-dots="{{true}}"
              autoplay="{{true}}"
              circular="{{true}}"
              interval="{{5000}}"
            >
              <carousel-item class="banner-carousel-item">
                <image class="banner-img" src="{{banner2Img}}" c-bind:tap="goToPage" data-url="quickExp"  data-path="./home/"></image>
              </carousel-item>
              <carousel-item class="banner-carousel-item">
                <image class="banner-img" src="{{bannerImg}}"></image>
              </carousel-item>
      </carousel>
 </view>
```

```CSS
.banner-container {
  width: 750cpx;
  height: 160cpx;
}

.banner-carousel {
  height: 160cpx;
}

.banner-carousel-item {
  padding: 0 26cpx;
}

.banner-img {
  width: 698cpx;
  height: 160cpx;
  border-radius: 12cpx;
}
```

当前环境依赖：

```JSON
 "dependencies": {
    "chameleon-api": "^0.3.0",
    "chameleon-bridge": "^0.1.1",
    "chameleon-runtime": "^0.1.0",
    "chameleon-store": "0.0.3",
    "chameleon-ui-builtin": "0.0.7-alpha.5",
    "cml-ui": "^0.1.0"
  }
```
